### ISSUE TITLE
[Bug] Colorizer drop block used to colorize

### ISSUE THREAD

**Issue by drakray** [grim3212/AssortedDecor#1] opened 2020-11-11 22:23 UTC
assorteddecor-1.16.3-1.0.0.jar
Forge .25
~~SP~~ MP

Breaking a Colorizer Wall give the wall AND the block use as color
Placing the Colorizer Wall and coloring it again with the wand, then breaking give it again

**Comment by grim3212** [comment] 2020-11-12 14:45
@drakray Are you still seeing this with 1.16.4 version? Nothing has changed other than the version change but I can't reproduce this.

**Comment by drakray** [comment] 2020-11-12 16:33
I didnt tried yet, because my pack is 1.16.3, but I play on a server
I'll try in single player

**Comment by grim3212** [comment] 2020-11-12 17:25
Ah okay let me know. It might be a server issue as I only tested it on single player.

**Comment by grim3212** [comment] 2020-11-13 14:25
Alright looks like this is an issue with 1.16.3 version. 1.16.4 does not have the same problem. Weird since I didn't make any code changes between the two versions.

Edit: Nevermind I am just an idiot. Been a while lol. I had my config setup wrong and now I see what the issue is.

**Comment by grim3212** [comment] 2020-11-13 14:38
Fixed with ecefc0e

**Closed as completed by grim3212** 2020-11-13 14:38 UTC

**Comment by drakray** [comment] 2020-11-13 14:42
Not problem, I'm a coder myself, I know how thing tend to slip by after some time lol XD
Does the 1.16.4 version work on 1.16.3?

**Comment by grim3212** [comment] 2020-11-13 14:59
From what it sounds like from the Minecraft Forge team, 1.16.3 mods should load on 1.16.4 but not the other way around.

From their changelog; "Support backwards loading 1.16.3 mods in 1.16.4, because we are able to do that"

**Comment by drakray** [comment] 2020-11-13 15:01
Ok thank you, I'll look into porting my pack :)
